apiVersion: v1    
kind: Secret
metadata:
  name: external-dns-hydra-secret
  namespace: external-dns
type: Opaque
data:
  HYDRA_URI: base64encodedUri
  HYDRA_TOKEN_NAME: base64encodedTokenName
  HYDRA_TOKEN_PASS: base64encodedTokenPass
